version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    environment:
        DB_SERVER: db
        DB_USER: bpm2025_user
        DB_PWD: bpm2025_password
        DB_NAME: bpm2025_db
        LOG_FILENAME: bpm2025_log.txt
    build:
        context: ./php
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
        - ./php/src:/var/www/html/
    ports:
        - 8100:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: bpm2025_root_password
        MYSQL_DATABASE: bpm2025_db
        MYSQL_USER: bpm2025_user
        MYSQL_PASSWORD: bpm2025_password
    ports:
        - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8181:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db